controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    ack_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

ack_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    traction_track_width: 0.177
    wheelbase: 0.172
    traction_wheels_radius: 0.032
    traction_joints_names: ['rear_right_wheel_joint', 'rear_left_wheel_joint']
    steering_joints_names: ['front_right_steering_joint', 'front_left_steering_joint']
    
    #open_loop
    #reduce_wheel_speed_until_steering_reached


# joint_broad:
#   ros__parameters: